
services:
  db:
    image: mysql
    environment:
      ENV: ${ENV}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ray", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  zookeeper:
    image: wurstmeister/zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc -w 2 localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - zookeeper-data:/data

  kafka:
    image: wurstmeister/kafka
    command: >
      bash -c "rm -rf /kafka/kafka-logs/meta.properties && start-kafka.sh"
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka/kafka-logs
    depends_on:
      - "zookeeper"

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - SERVICE_NAME=receiver
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      kafka:
        condition: service_healthy


  storage:
    build:
      context: .
      dockerfile: storage/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - ENV=dev
      - SERVICE_NAME=storage
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy

  processing:
    build:
      context: .
      dockerfile: processing/Dockerfile
    ports:
      - "8100:8100"
    environment:
      - ENV=dev
      - SERVICE_NAME=processing
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data/processing:/app/data
    depends_on:
      - storage

  analyzer:
    build:
      context: .
      dockerfile: analyzer/Dockerfile
    ports:
      - "8110:8110"
    environment:
      - ENV=dev
      - SERVICE_NAME=analyzer
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - kafka

volumes:
  mysql_data:
  zookeeper-data:
