version: 1
datastore:
  filename: /app/data/stats.json
scheduler:
  interval: 5
eventstore:
  conditions:
    url: http://storage/storage/traffic/conditions
  incidents:
    url: http://storage/storage/traffic/incidents
